/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calendarforproject;

import com.toedter.calendar.JDateChooser;
import java.awt.Font;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.util.prefs.Preferences;
import javax.swing.SwingUtilities;

/**
 * Login class represents the form for sign in or sign up and deals with the user database to authenticate the users.
 * 
 * @author Sadat Arefin Rafat,180041106
 * @author Shams Tanveer Jim,180041107
 * @author Faysal Mahmud,180041117
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    String first_name = "", last_name = "", email_id = "", phone_no = "", password = "";
    String confirm_password = "", address = "", security_answer = "AA", date_of_birth = "", security_question = "";
    static String login_email_id = "";
    String login_password = "", database_password = "";
    Connection myconn = null;
    Statement mysmt = null;
    ResultSet myrs = null;
    int login_flag = 0;

    int checkbox_flag = 0;
    JPanel f2 = new JPanel();
    JLabel for_message = new JLabel();
    

     
          Preferences pref;
    public void rememberMe(){
        pref=Preferences.userNodeForPackage(this.getClass());
        String value=pref.get("emailid","");
        String value1=pref.get("password","");
        System.out.println(login_email_id);
        if (!value.equals("") && !value1.equals("")) {
            login_email_id=value;
            login_password=value1;
          signinemailidText.setText(value);
          loginPasswordField.setText(value1);
          remember.setSelected(true);
        }     
    }
     public void remove(){
         signinemailidText.setText("");
          loginPasswordField.setText("");
       pref.remove("emailid");
       pref.remove("password");
       remember.setSelected(false);
    }

    
    public Login() {
        initComponents();
        
        rememberMe();
        
        signupPanel.setVisible(false);
        //signinPanel.setVisible(false);
        
    }
    
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        signupLabel = new javax.swing.JLabel();
        signinLabelButton = new javax.swing.JLabel();
        firstnameText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        userName = new javax.swing.JLabel();
        lastnameText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        userName3 = new javax.swing.JLabel();
        emailidText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        userName5 = new javax.swing.JLabel();
        addressText = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        userName7 = new javax.swing.JLabel();
        phonenoText = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        userName9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        userName11 = new javax.swing.JLabel();
        dbirthText = new com.toedter.calendar.JDateChooser();
        userName12 = new javax.swing.JLabel();
        userName13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        checkBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        signupButton = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        conpasswordField = new javax.swing.JPasswordField();
        signinPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        signupLabelButton = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        signinemailidText = new javax.swing.JTextField();
        userName1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        userName2 = new javax.swing.JLabel();
        forgetpasswordLabel = new javax.swing.JLabel();
        loginPasswordField = new javax.swing.JPasswordField();
        remember = new javax.swing.JCheckBox();
        realsigninButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2000, 1050));

        signupPanel.setBackground(new java.awt.Color(255, 255, 255));
        signupPanel.setPreferredSize(new java.awt.Dimension(1900, 950));
        signupPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/loginimage.png"))); // NOI18N
        signupPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 34, 770, 910));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (2).png"))); // NOI18N
        jPanel2.add(signupLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        signinLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (3).png"))); // NOI18N
        signinLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signinLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signinLabelButtonMouseExited(evt);
            }
        });
        jPanel2.add(signinLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 11, -1, -1));

        firstnameText.setBackground(new java.awt.Color(0, 0, 51));
        firstnameText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        firstnameText.setForeground(new java.awt.Color(255, 255, 255));
        firstnameText.setText("Enter First Name");
        firstnameText.setBorder(null);
        firstnameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnameTextMouseClicked(evt);
            }
        });
        firstnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextActionPerformed(evt);
            }
        });
        jPanel2.add(firstnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 470, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 470, 20));

        userName.setBackground(new java.awt.Color(255, 255, 255));
        userName.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("First Name");
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        lastnameText.setBackground(new java.awt.Color(0, 0, 51));
        lastnameText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lastnameText.setForeground(new java.awt.Color(255, 255, 255));
        lastnameText.setText("Enter Last Name");
        lastnameText.setBorder(null);
        lastnameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastnameTextMouseClicked(evt);
            }
        });
        lastnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameTextActionPerformed(evt);
            }
        });
        jPanel2.add(lastnameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 470, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 470, 20));

        userName3.setBackground(new java.awt.Color(255, 255, 255));
        userName3.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName3.setForeground(new java.awt.Color(255, 255, 255));
        userName3.setText("Last Name");
        jPanel2.add(userName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        emailidText.setBackground(new java.awt.Color(0, 0, 51));
        emailidText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        emailidText.setForeground(new java.awt.Color(255, 255, 255));
        emailidText.setText("Enter Email Id");
        emailidText.setBorder(null);
        emailidText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailidTextMouseClicked(evt);
            }
        });
        emailidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidTextActionPerformed(evt);
            }
        });
        jPanel2.add(emailidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 470, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 470, 20));

        userName5.setBackground(new java.awt.Color(255, 255, 255));
        userName5.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName5.setForeground(new java.awt.Color(255, 255, 255));
        userName5.setText("Email Id");
        jPanel2.add(userName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        addressText.setBackground(new java.awt.Color(0, 0, 51));
        addressText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        addressText.setForeground(new java.awt.Color(255, 255, 255));
        addressText.setText("Enter Address");
        addressText.setBorder(null);
        addressText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTextMouseClicked(evt);
            }
        });
        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        jPanel2.add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 470, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 470, 20));

        userName7.setBackground(new java.awt.Color(255, 255, 255));
        userName7.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName7.setForeground(new java.awt.Color(255, 255, 255));
        userName7.setText("Address");
        jPanel2.add(userName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        phonenoText.setBackground(new java.awt.Color(0, 0, 51));
        phonenoText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        phonenoText.setForeground(new java.awt.Color(255, 255, 255));
        phonenoText.setText("Enter Phone Number");
        phonenoText.setBorder(null);
        phonenoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonenoTextMouseClicked(evt);
            }
        });
        phonenoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoTextActionPerformed(evt);
            }
        });
        jPanel2.add(phonenoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 470, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 470, 20));

        userName9.setBackground(new java.awt.Color(255, 255, 255));
        userName9.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName9.setForeground(new java.awt.Color(255, 255, 255));
        userName9.setText("Confirm Password");
        jPanel2.add(userName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, -1, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, 470, 20));

        userName11.setBackground(new java.awt.Color(255, 255, 255));
        userName11.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName11.setForeground(new java.awt.Color(255, 255, 255));
        userName11.setText("Date of Birth");
        jPanel2.add(userName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        dbirthText.setBackground(new java.awt.Color(255, 255, 255));
        dbirthText.setDateFormatString("yyyy-MM-dd");
        dbirthText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.add(dbirthText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 370, 30));

        userName12.setBackground(new java.awt.Color(255, 255, 255));
        userName12.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName12.setForeground(new java.awt.Color(255, 255, 255));
        userName12.setText("Phone Number");
        jPanel2.add(userName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        userName13.setBackground(new java.awt.Color(255, 255, 255));
        userName13.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName13.setForeground(new java.awt.Color(255, 255, 255));
        userName13.setText("Password");
        jPanel2.add(userName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, 470, 20));

        checkBox.setBackground(new java.awt.Color(0, 0, 51));
        checkBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkBoxMouseClicked(evt);
            }
        });
        jPanel2.add(checkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agree With Term And Condition");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 790, -1, 20));

        signupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (4).png"))); // NOI18N
        signupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupButtonMouseClicked(evt);
            }
        });
        jPanel2.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, -1, -1));

        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 470, 30));

        conpasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conpasswordFieldMouseClicked(evt);
            }
        });
        conpasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(conpasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 470, 30));

        signupPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 34, 840, 910));

        signinPanel.setBackground(new java.awt.Color(255, 255, 255));
        signinPanel.setPreferredSize(new java.awt.Dimension(1900, 950));
        signinPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/loginimage.png"))); // NOI18N
        signinPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 34, 810, 880));

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (3).png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 11, -1, -1));

        signupLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (2).png"))); // NOI18N
        signupLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupLabelButtonMouseExited(evt);
            }
        });
        jPanel4.add(signupLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 140, -1));
        jPanel4.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 470, 20));

        signinemailidText.setBackground(new java.awt.Color(0, 0, 51));
        signinemailidText.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        signinemailidText.setForeground(new java.awt.Color(255, 255, 255));
        signinemailidText.setText("Enter Email ID");
        signinemailidText.setBorder(null);
        signinemailidText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinemailidTextMouseClicked(evt);
            }
        });
        signinemailidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinemailidTextActionPerformed(evt);
            }
        });
        jPanel4.add(signinemailidText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 470, 30));

        userName1.setBackground(new java.awt.Color(255, 255, 255));
        userName1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName1.setForeground(new java.awt.Color(255, 255, 255));
        userName1.setText("Enter Email ID");
        jPanel4.add(userName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 470, 20));

        userName2.setBackground(new java.awt.Color(255, 255, 255));
        userName2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        userName2.setForeground(new java.awt.Color(255, 255, 255));
        userName2.setText("Enter Password");
        jPanel4.add(userName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        forgetpasswordLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        forgetpasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgetpasswordLabel.setText("Forgot Paaword?");
        forgetpasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetpasswordLabelMouseClicked(evt);
            }
        });
        jPanel4.add(forgetpasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 750, 190, -1));

        loginPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPasswordFieldMouseClicked(evt);
            }
        });
        loginPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordFieldActionPerformed(evt);
            }
        });
        jPanel4.add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 470, 30));

        remember.setBackground(new java.awt.Color(0, 0, 51));
        remember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        remember.setForeground(new java.awt.Color(255, 255, 255));
        remember.setText("Remeber Me");
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });
        jPanel4.add(remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        realsigninButton.setBackground(new java.awt.Color(0, 51, 240));
        realsigninButton.setForeground(new java.awt.Color(255, 255, 255));
        realsigninButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (8).png"))); // NOI18N
        realsigninButton.setBorderPainted(false);
        realsigninButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realsigninButtonActionPerformed(evt);
            }
        });
        jPanel4.add(realsigninButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 130, 60));

        signinPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 34, 840, 880));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1849, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signinPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextActionPerformed
        // TODO add your handling code here:
        first_name = firstnameText.getText();
    }//GEN-LAST:event_firstnameTextActionPerformed

    private void lastnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameTextActionPerformed
        // TODO add your handling code here:
        last_name = lastnameText.getText();
    }//GEN-LAST:event_lastnameTextActionPerformed

    private void emailidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidTextActionPerformed
        // TODO add your handling code here:
        email_id = emailidText.getText();
    }//GEN-LAST:event_emailidTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
        address = addressText.getText();
    }//GEN-LAST:event_addressTextActionPerformed

    private void phonenoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoTextActionPerformed
        // TODO add your handling code here:
        phone_no = phonenoText.getText();
    }//GEN-LAST:event_phonenoTextActionPerformed

    private void signinLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinLabelButtonMouseClicked
        // TODO add your handling code here:
        signupPanel.setVisible(false);
        signinPanel.setVisible(true);
    }//GEN-LAST:event_signinLabelButtonMouseClicked

    private void signinLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinLabelButtonMouseEntered
        // TODO add your handling code here:
        signinLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (5).png"))); // NOI18N
    }//GEN-LAST:event_signinLabelButtonMouseEntered

    private void signinemailidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinemailidTextActionPerformed
        // TODO add your handling code here:
        login_email_id = signinemailidText.getText();
    }//GEN-LAST:event_signinemailidTextActionPerformed

    private void signupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupButtonMouseClicked
        // TODO add your handling code here:
        JPanel f = new JPanel();
        f.setLayout(new GridLayout(4, 1));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        date_of_birth = sdf.format(dbirthText.getDate());
        JLabel question_panel = new JLabel("Create A Security Question");
        JLabel answer_panel = new JLabel("Answer The Question.");
        JTextArea question_text = new JTextArea("");
        JTextArea answer_text = new JTextArea("");
        Font f1 = new Font("TimesRoman", Font.BOLD, 20);
        for_message.setFont(f1);
        question_panel.setFont(f1);
        question_text.setFont(f1);
        answer_panel.setFont(f1);
        answer_text.setFont(f1);
        f.add(question_panel);
        f.add(question_text);
        f.add(answer_panel);
        f.add(answer_text);
        f.setSize(300, 300);

        if (checkbox_flag == 1) {
            if (password.equals(confirm_password)) {
                if (first_name != "" && last_name != "" && phone_no != "" && address != "" && date_of_birth != "") {
                    int result = JOptionPane.showConfirmDialog(null, f,
                            "Security Purpose", JOptionPane.OK_CANCEL_OPTION);

                    if (result == JOptionPane.OK_OPTION) {
                        security_answer = answer_text.getText();
                        security_question = question_text.getText();
                        if (!security_answer.isEmpty() && !security_question.isEmpty()) {

                            try {
                                myconn = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/rdbms_database", "rdbms_user", "Iutuser18");
                                mysmt = myconn.createStatement();

                                String sql = "insert into user_table(emailid,password,phoneno,dobirth,secanswer,secquestion) values(?,?,?,?,?,?)";
                                PreparedStatement pstmt = myconn.prepareStatement(sql);
                                pstmt.setString(1, email_id);
                                pstmt.setString(2, password);
                                pstmt.setString(3, phone_no);
                                pstmt.setString(4, date_of_birth);
                                pstmt.setString(5, security_answer);
                                pstmt.setString(6, security_question);
                                pstmt.executeUpdate();
                                mysmt.close();
                                myconn.close();
                                pstmt.close();
                                login_email_id = email_id;
                                for_message.setText("Sign Up Successfully");
                                f2.add(for_message);
                                JOptionPane.showMessageDialog(null, f2);
                                dispose();
                                calendar obj1 = new calendar();
                                obj1.setBounds(0, 0, 2000, 1050);
                                obj1.setVisible(true);

                            } catch (SQLException e) {
                                for_message.setText("" + e);
                                f2.add(for_message);
                                JOptionPane.showMessageDialog(null, f2);
                            }
                        } else {
                            for_message.setText("No Field Should Be Empty.");
                            f2.add(for_message);
                            JOptionPane.showMessageDialog(null, f2);
                        }
                    } else {
                        for_message.setText("You Have to Go Through Security Purpose " + "\n" + "For Recovering Password.");
                        f2.add(for_message);
                        JOptionPane.showMessageDialog(null, f2);
                    }

                } else {
                    for_message.setText("No Field Should Be Empty.");
                    f2.add(for_message);
                    JOptionPane.showMessageDialog(null, f2);
                }
            } else {
                for_message.setText("Confirm Password Does not Match.Write Again. ");
                f2.add(for_message);
                JOptionPane.showMessageDialog(null, f2);
            }
        } else {
            for_message.setText("Please Agree with Our Terms and Condition.");
            f2.add(for_message);
            JOptionPane.showMessageDialog(null, f2);
        }
    }//GEN-LAST:event_signupButtonMouseClicked

    private void checkBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkBoxMouseClicked
        // TODO add your handling code here:
        if (checkBox.isSelected()) {
            checkbox_flag = 1;
        } else {
            checkbox_flag = 0;
        }

    }//GEN-LAST:event_checkBoxMouseClicked

   
    private void forgetpasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpasswordLabelMouseClicked
        // TODO add your handling code here:
        signupPanel.setVisible(false);
        signinPanel.setVisible(true);
        String a, b, c, d, e = null, f, g, h, i;
        int security_flag = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        JPanel sc = new JPanel();
        sc.setLayout(new GridLayout(10, 1));
        JDateChooser dateofbirth = new JDateChooser();
        JTextArea question_text = new JTextArea();
        JTextArea answer_text = new JTextArea();
        JTextField phone_text = new JTextField(15);
        JTextField email_text = new JTextField(25);
        JLabel dob = new JLabel("Enter Your Date of Birth");
        JLabel que = new JLabel("The Question You Provided");
        JLabel ans = new JLabel("Write The Answer You Provided");
        JLabel phn = new JLabel("Write The Phone Number You Provided");
        JLabel eid = new JLabel("Write Your Emial ID");
        Font f1 = new Font("TimesRoman", Font.BOLD, 20);
        for_message.setFont(f1);
        eid.setFont(f1);
        dob.setFont(f1);
        que.setFont(f1);
        ans.setFont(f1);
        phn.setFont(f1);
        dateofbirth.setFont(f1);
        question_text.setFont(f1);
        answer_text.setFont(f1);
        phone_text.setFont(f1);
        email_text.setFont(f1);

        sc.add(eid);
        sc.add(email_text);
        sc.add(phn);
        sc.add(phone_text);
        sc.add(dob);
        sc.add(dateofbirth);
        sc.add(ans);
        sc.add(answer_text);

        int result = JOptionPane.showConfirmDialog(null, sc,
                "Forgot Password", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            login_email_id = email_text.getText();
            a = phone_text.getText();
            b = sdf.format(dateofbirth.getDate());
            d = answer_text.getText();

            if (!a.isEmpty() && !b.isEmpty() && !d.isEmpty()) {
                try {
                    myconn = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/rdbms_database", "rdbms_user", "Iutuser18");
                    mysmt = myconn.createStatement();
                    myrs = mysmt.executeQuery("select password,phoneno,dobirth,secanswer,secquestion from user_table where emailid='" + login_email_id + "'");

                    while (myrs.next()) {
                        e = myrs.getString("password");
                        f = myrs.getString("phoneno");
                        g = myrs.getString("dobirth");
                        h = myrs.getString("secanswer");
                        i = myrs.getString("secquestion");
                        if (a.equals(f) && b.equals(g) && d.equals(h)) {
                            security_flag = 1;
                        } else {
                            security_flag = 0;
                        }
                    }

                    myrs.close();
                    mysmt.close();
                    myconn.close();
                    if (security_flag == 1) {
                        for_message.setText("Your Given Password is :" + e);
                        f2.add(for_message);
                        JOptionPane.showMessageDialog(null, f2);
                    } else {
                        for_message.setText("Error In Information");
                        f2.add(for_message);
                        JOptionPane.showMessageDialog(null, f2);
                    }

                } catch (SQLException e1) {
                    for_message.setText("" + e1);
                    f2.add(for_message);
                    JOptionPane.showMessageDialog(null, f2);
                }
            } else {
                for_message.setText("No Field Should Be Empty.");
                f2.add(for_message);
                JOptionPane.showMessageDialog(null, f2);
            }
        }
    }//GEN-LAST:event_forgetpasswordLabelMouseClicked

    private void signupLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelButtonMouseClicked
        // TODO add your handling code here:
        signupPanel.setVisible(true);
        signinPanel.setVisible(false);
    }//GEN-LAST:event_signupLabelButtonMouseClicked

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
        password = passwordField.getText();
        System.out.println(password);

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void conpasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordFieldActionPerformed
        // TODO add your handling code here:
        confirm_password = conpasswordField.getText();
        System.out.println(confirm_password);
    }//GEN-LAST:event_conpasswordFieldActionPerformed

    private void loginPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordFieldActionPerformed
        // TODO add your handling code here:
        login_password = loginPasswordField.getText();
    }//GEN-LAST:event_loginPasswordFieldActionPerformed

    private void firstnameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameTextMouseClicked
        // TODO add your handling code here:
        firstnameText.setText(first_name);
    }//GEN-LAST:event_firstnameTextMouseClicked

    private void lastnameTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastnameTextMouseClicked
        // TODO add your handling code here:
        lastnameText.setText(last_name);
    }//GEN-LAST:event_lastnameTextMouseClicked

    private void emailidTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailidTextMouseClicked
        // TODO add your handling code here:
        emailidText.setText(email_id);
    }//GEN-LAST:event_emailidTextMouseClicked

    private void addressTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTextMouseClicked
        // TODO add your handling code here:
        addressText.setText(address);
    }//GEN-LAST:event_addressTextMouseClicked

    private void phonenoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonenoTextMouseClicked
        // TODO add your handling code here:
        phonenoText.setText(phone_no);
    }//GEN-LAST:event_phonenoTextMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        // TODO add your handling code here:
        passwordField.setText(password);
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void conpasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conpasswordFieldMouseClicked
        // TODO add your handling code here:
        conpasswordField.setText(confirm_password);
    }//GEN-LAST:event_conpasswordFieldMouseClicked

    private void signinemailidTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinemailidTextMouseClicked
        // TODO add your handling code here:
        signinemailidText.setText(login_email_id);
    }//GEN-LAST:event_signinemailidTextMouseClicked

    private void loginPasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPasswordFieldMouseClicked
        // TODO add your handling code here:
        loginPasswordField.setText(login_password);
    }//GEN-LAST:event_loginPasswordFieldMouseClicked

    private void signupLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelButtonMouseEntered
        // TODO add your handling code here:
        signupLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (1).png"))); 
    }//GEN-LAST:event_signupLabelButtonMouseEntered

    private void signupLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupLabelButtonMouseExited
        // TODO add your handling code here:
        signupLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (2).png"))); 
    }//GEN-LAST:event_signupLabelButtonMouseExited

    private void signinLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinLabelButtonMouseExited
        // TODO add your handling code here:
        signinLabelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calendarforproject/button (3).png"))); 
    }//GEN-LAST:event_signinLabelButtonMouseExited

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberActionPerformed

    private void realsigninButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realsigninButtonActionPerformed
        // TODO add your handling code here:
         for_message.setFont(new Font("TimesRoman", Font.BOLD, 20));
        if (!login_email_id.equals("") && !login_password.equals("")) {
            try {
                myconn = DriverManager.getConnection("jdbc:mysql://db4free.net:3306/rdbms_database", "rdbms_user", "Iutuser18");
                mysmt = myconn.createStatement();
                myrs = mysmt.executeQuery("select password from user_table where emailid='" + login_email_id + "'");

                while (myrs.next()) {
                    database_password = myrs.getString("password");
                    if (database_password.equals(login_password)) {
                        login_flag = 1;
                        if(remember.isSelected()){
                         
                            pref.put("emailid",login_email_id);
                            pref.put("password",login_password);
                        }
                        else{
                          
                            pref.remove("emailid");
                            pref.remove("password");
                        }
                        System.out.println("Successful");
                    } else {
                        login_flag = 0;
                    }
                }

                myrs.close();
                mysmt.close();
                myconn.close();
                if (login_flag == 1) {
                    for_message.setText("Sign In Successfully.");
                    f2.add(for_message);
                    JOptionPane.showMessageDialog(null, f2);
                    dispose();
                    calendar obj1 = new calendar();
                    obj1.setBounds(0, 0, 2000, 1050);
                    obj1.setVisible(true);
                } else {
                    for_message.setText("Error in Email id or Password.");
                    f2.add(for_message);
                    JOptionPane.showMessageDialog(null, f2);

                }

            } catch (SQLException e) {
                for_message.setText("" + e);
                f2.add(for_message);
                JOptionPane.showMessageDialog(null, f2);
            }
        } else {
            for_message.setText("Email ID and Password Can Not Be Empty");
            f2.add(for_message);
            JOptionPane.showMessageDialog(null, f2);
        }
    }//GEN-LAST:event_realsigninButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressText;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JPasswordField conpasswordField;
    private com.toedter.calendar.JDateChooser dbirthText;
    private javax.swing.JTextField emailidText;
    private javax.swing.JTextField firstnameText;
    private javax.swing.JLabel forgetpasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastnameText;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phonenoText;
    private javax.swing.JButton realsigninButton;
    private javax.swing.JCheckBox remember;
    private javax.swing.JLabel signinLabelButton;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JTextField signinemailidText;
    private javax.swing.JLabel signupButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JLabel signupLabelButton;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userName1;
    private javax.swing.JLabel userName11;
    private javax.swing.JLabel userName12;
    private javax.swing.JLabel userName13;
    private javax.swing.JLabel userName2;
    private javax.swing.JLabel userName3;
    private javax.swing.JLabel userName5;
    private javax.swing.JLabel userName7;
    private javax.swing.JLabel userName9;
    // End of variables declaration//GEN-END:variables
}
